### ISSUE TITLE
нажимаю "проверка на дубли"

### ISSUE THREAD

**Issue by ChupakabraMSK** [qiwichupa/RussianFIO2AD#4]
программа вылетает

2021-11-05 19:12:48,451	main-gui  	CRITICAL	main      	unhandled_exception                	587   	Uncaught exception
Traceback (most recent call last):
  File "main.py", line 259, in testADAccounts
  File "main.py", line 360, in test_user_in_ad
  File "pyad\adquery.py", line 78, in execute_query
  File "<COMObject ADODB.Command>", line 3, in Execute
  File "win32com\client\dynamic.py", line 314, in _ApplyTypes_
pywintypes.com_error: (-2147352567, 'Ошибка.', (0, 'Provider', 'Произошла одна или несколько ошибок во время обработки команды.', None, 1240640, -2147217900), None)

**Comment by qiwichupa** [comment]
А чем заполнены поля с логинами и т.п.?

**Comment by qiwichupa** [comment]
Может быть какое-то имя OU некорректно обрабатывается. Помнится были определенные вилы с названиями OU и групп, содержащими символы, требующие экранирования.

**Comment by ChupakabraMSK** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/88263306/140549015-2211b253-94f2-468c-840d-006a5c0ff750.png)
причем создаются учетки успешно - эти же
